on: [push]

name: Dead Code analysis

jobs:
  deadnix:
    name: Deadnix
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v2
      - uses: cachix/install-nix-action@v16
      - uses: cachix/cachix-action@v10
        with:
          name: deadnix
      - uses: astro/deadnix-action@main
